# 1. Obtención de los datos
## 1.1 Contexto
La informacion recolectada se encuentra en un archivo con formtato CSV (WeatherHistoryData_Cd_Juarez) el cual cuenta con 21 columnas y 209,424 filas.

El proyecto sera sobre el Clima en Ciudad Juárez, Chihuahua, México (lat: 31.70983875, lon: -106.4621016), que para ser mas precisos, predecir el clima en una fecha, primeramente sera estatica, y luego pasara a dinamica, es decir, cualquier otra fecha. Sera se usara Machine Learning, para el entrenemiento de los datos y despues del aprendijaze se realizaran ciertas pruebas con fechas.

Se prevee calcular no solo la temeperatura, sino que, tambien el punto de rocio, la direccion del viento, la altura de las nubes, la temperatura del suelo, la evaporacion, etc. Esto y mas con 18 parametros que se cuentan en el dataset.

Para efectuar esto, como se menciono anteriormente se usara ML, asi como tambien las liebrerias, como Pandas, MatPlotLib, Seaborn y Numpy.

# 2. Exploracion de los datos
Para dar inicio al proyecto, primero debemos dar una mirada al dataset que sera analizado.

In [18]:
# Lectura del dataset
import pandas as pd

# Lectura del CSV
ruta_csv="../../csv/WHData_Cd_Juarez.csv"

# Leyendo CSV con Pandas
datajuarez=pd.read_csv(ruta_csv,encoding='latin-1')

#Mostra dataframe
print(datajuarez.shape)
datajuarez.head(10)

(209424, 26)

,name,lat,lon,time,time_iso,time_usa,time_num_usa,v_10u,v_10v,v_2d,...,v_msl,v_pev,v_ptype,v_stl1,v_swvl1,v_tcc,v_tp,v_wa,v_wd,v_ws
0,Ciudad Juarez,31.709839,-106.462102,946684800,2000-01-01T00:00:00,01/01/2000,36526,-1.669281,-0.020920,7.480493,...,1012.635625,-1.250000e-05,0,13.064264,0.137127,0.152496,0.0,89,este,1.669412
1,Ciudad Juarez,31.709839,-106.462102,946688400,2000-01-01T01:00:00,01/01/2000,36526,-1.951294,-0.468689,8.055566,...,1012.456250,-6.860000e-07,0,12.453210,0.137084,0.236725,0.0,76,este,2.006793
2,Ciudad Juarez,31.709839,-106.462102,946692000,2000-01-01T02:00:00,01/01/2000,36526,-1.763443,-0.294388,5.953119,...,1012.368125,6.660000e-07,0,10.392664,0.137066,0.579987,0.0,81,este,1.787847
3,Ciudad Juarez,31.709839,-106.462102,946695600,2000-01-01T03:00:00,01/01/2000,36526,-1.436081,0.382751,5.892938,...,1012.543125,1.220000e-06,0,8.273584,0.137028,0.482239,0.0,105,este,1.486212
4,Ciudad Juarez,31.709839,-106.462102,946699200,2000-01-01T04:00:00,01/01/2000,36526,-0.908798,1.725983,5.761438,...,1012.673750,1.130000e-06,0,7.544336,0.137005,0.411499,0.0,152,sureste,1.950623
5,Ciudad Juarez,31.709839,-106.462102,946702800,2000-01-01T05:00:00,01/01/2000,36526,-0.377380,2.554306,5.132959,...,1012.659375,2.290000e-06,0,6.913049,0.136968,0.614685,0.0,172,sur,2.582033
6,Ciudad Juarez,31.709839,-106.462102,946706400,2000-01-01T06:00:00,01/01/2000,36526,0.356659,2.629395,4.263757,...,1012.491250,3.490000e-06,0,6.220911,0.136947,0.535614,0.0,188,sur,2.653473
7,Ciudad Juarez,31.709839,-106.462102,946710000,2000-01-01T07:00:00,01/01/2000,36526,1.176437,2.084335,3.994012,...,1012.315000,2.970000e-06,0,5.943872,0.136921,0.141052,0.0,209,sudoeste,2.393420
8,Ciudad Juarez,31.709839,-106.462102,946713600,2000-01-01T08:00:00,01/01/2000,36526,1.626434,1.169067,4.224725,...,1012.189375,3.070000e-06,0,5.993433,0.136891,0.577209,0.0,234,sudoeste,2.003000
9,Ciudad Juarez,31.709839,-106.462102,946717200,2000-01-01T09:00:00,01/01/2000,36526,1.527802,0.984741,4.503931,...,1011.985000,2.480000e-06,0,5.963464,0.136874,0.652557,0.0,237,sudoeste,1.817661

## 2.1 Tipos de datos

Aqui veremos los tipos de datos o parametros que tenemos en el dataset, como es una proyecto **Metereologico**, en su mayoria sera datos nuemricos, y uno que otros de cadena de caracteres. Todos los parametros, variables o datos, son en *Unidad Metrica* en el caso de los numericos.

| Variable | Interpretatio (US) | Interpretación (ES) | Unidad Metrica |
| --- | --- | --- | --- |
| v_2t | 2m air temperature	 | Temperatura del aire en 2m | Celsius
| v_2d | 2m dew point	 | Punto de rocío | Celsius
| v_10u | U-wind component on 10m	 | .843 | Hectopascales
| v_10v | V-wind component on 10m	 | .843 | Metros por segundo	
| v_i10fg | 10m wind gust	 | .843 | Metros por segundo
| v_cbh | Cloud base height	 | Altura de la nube | Metros
| v_tcc	 | Total cloud cover | Nubosidad total| *Se maneja por rango*
| v_ptype | Precipitation type | Tipo de precipitación | *Se maneja por rango*
| v_tp | Hourly accumulated precipitation | .843 | Milimitros
| v_stl1 | Soil temperature at 0-7 cm | .843 | Celsius
| v_swvl1 | Volumetric soil water at 0-7 cm | .843 | Metros cubicos
| v_e | Evaporation | .843 | Metros
| v_pev | Potential evaporation	| .843 | Metros
| v_mer | Mean evaporation rate	 | .843 | Kilogramos por metro cuadrado por segundo	
| v_mper | Mean potential evaporation rate | .843 | Kilogramos por metro cuadrado por segundo	
| v_ws | Wind speed	 | .843 | Metros por segundo	
| v_wa | Wind angle	 | .843 | Grados
| v_wd | Wind direction | .843 | *Se maneja por rango*
| v_msl | Mean sea level pressure | .843 | *Se maneja por rango*

## 2.2 Descripcion de variables

### 2.2.1 Variables categoricas

In [19]:
datajuarez.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209424 entries, 0 to 209423
Data columns (total 26 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   name          209424 non-null  object
 1   lat           209424 non-null  float64
 2   lon           209424 non-null  float64
 3   time          209424 non-null  int64
 4   time_iso      209424 non-null  object
 5   time_usa      209424 non-null  object
 6   time_num_usa  209424 non-null  int64
 7   v_10u         209424 non-null  float64
 8   v_10v         209424 non-null  float64
 9   v_2d          209424 non-null  float64
 10  v_2t          209424 non-null  float64
 11  v_cbh         209424 non-null  float64
 12  v_e           209424 non-null  float64
 13  v_i10fg       209424 non-null  float64
 14  v_mer         209424 non-null  float64
 15  v_mper        209424 non-null  float64
 16  v_msl         209424 non-null  float64
 17  v_pev         209424 non-null  float64
 18  v_ptype       209424 non-null  int64
 19  v_stl1        209424 non-null  float64
 20  v_swvl1       209424 non-null  float64
 21  v_tcc         209424 non-null  float64
 22  v_tp          209424 non-null  float64
 23  v_wa          209424 non-null  int64
 24  v_wd          209424 non-null  object
 25  v_ws          209424 non-null  float64
dtypes: float64(18), int64(4), object(4)
memory usage: 41.5+ MB

### 2.2.2 Variables numericas
Vemos a detalles lo que ocurren con cada variable numerica, y asi mismo las estadisticas descriptivas basicas.

In [20]:
datajuarez.describe()

,lat,lon,time,time_num_usa,v_10u,v_10v,v_2d,v_2t,v_cbh,v_e,...,v_mper,v_msl,v_pev,v_ptype,v_stl1,v_swvl1,v_tcc,v_tp,v_wa,v_ws
count,2.094240e+05,2.094240e+05,2.094240e+05,209424.000000,209424.000000,209424.000000,209424.000000,209424.000000,209424.000000,209424.000000,...,209424.000000,209424.000000,209424.000000,209424.000000,209424.000000,209424.000000,209424.000000,209424.000000,209424.000000,209424.000000
mean,3.170984e+01,-1.064621e+02,1.323646e+09,40888.500000,0.370038,0.509397,1.636508,18.807033,4100.225235,-0.000020,...,-0.000059,1014.235355,-0.000211,0.107380,20.860411,0.043263,0.311505,0.022371,183.193044,3.143997
std,1.065817e-14,8.526533e-14,2.176403e+08,2518.985222,3.235571,1.608619,8.590113,9.812463,1894.881206,0.000051,...,0.000072,6.077775,0.000258,0.496105,11.913696,0.044748,0.368586,0.160154,88.192662,1.888974
min,3.170984e+01,-1.064621e+02,9.466848e+08,36526.000000,-11.340240,-9.080811,-29.034842,-16.444403,27.896713,-0.000604,...,-0.000312,989.825625,-0.001124,0.000000,-13.263220,-0.004450,0.000000,0.000000,0.000000,0.005129
25%,3.170984e+01,-1.064621e+02,1.135166e+09,38707.000000,-1.902061,-0.491474,-4.939200,11.158350,3292.380371,-0.000013,...,-0.000107,1010.089375,-0.000385,0.000000,11.429391,0.023953,0.000000,0.000000,104.000000,1.801986
50%,3.170984e+01,-1.064621e+02,1.323646e+09,40888.500000,0.252632,0.550819,0.650781,19.598199,4100.225235,-0.000004,...,-0.000017,1013.525000,-0.000060,0.000000,20.848154,0.029167,0.114899,0.000000,195.000000,2.723756
75%,3.170984e+01,-1.064621e+02,1.512127e+09,43070.000000,2.425674,1.522297,8.666864,26.421793,4100.225235,-0.000001,...,-0.000003,1017.661406,-0.000012,0.000000,28.987253,0.039132,0.619781,0.000000,260.000000,4.082880
max,3.170984e+01,-1.064621e+02,1.700608e+09,45251.000000,15.362930,11.523743,24.166284,42.485254,14467.818360,0.000016,...,0.000005,1042.341250,0.000017,8.000000,53.994501,0.384890,1.000000,7.702827,359.000000,16.691450